<?php

/**
 * @file
 * Code for the Ulf Hjørring feature.
 */

include_once 'ulf_hjoerring_settings.features.inc';


/**
 * Add new role.
 *
 * @return array
 *   An array defining a role
 */
function ulf_hjoerring_settings_secure_permissions_roles() {
  return array(
    'company consultant',
    'company',
  );
}

/**
 * Implements hook_secure_permissions().
 */
function ulf_hjoerring_settings_secure_permissions($role) {
  $permissions = [];
  if($role == 'company consultant') {
    // by default company consultants have the same permissions as editors, with a few alterations
    $permissions = [
      'assign company consultant role',
      'assign company role',
      'create news_course_provider content',
      'create internship content',
      'edit any internship content',
      'edit own internship content',
      'create education content',
      'edit any education content',
      'edit own education content',
    ];

    $modules = module_implements('secure_permissions');
    foreach ($modules as $module) {
      $function = $module.'_secure_permissions';
      $add_permissions = $function('editor');
      if($add_permissions) {
        $permissions = array_merge($permissions, $add_permissions);
      }
    }

    $remove = [
      'assign editor role',
      'assign course provider role',
      'create course content',
      'edit any course content',
      'edit own course content',
      'create course_educators content',
      'edit any course_educators content',
      'edit own course_educators content',
    ];
    $permissions = array_diff($permissions, $remove);
  }

//  if($role == 'company') {
//    // companies should never actually log in, so their permissions doesn't matter
//    $permissions = [];
//  }

  return $permissions;
}

/**
 * Implements hook_menu_alter().
 *
 * Takes over the access callback for user profiles.
 */
function ulf_hjoerring_settings_menu_alter(&$items) {
  $items['user/%user']['access callback'] = 'ulf_hjoerring_settings_access';
}

/**
 * Access callback for user profiles.
 */
function ulf_hjoerring_settings_access($account = NULL) {
  global $user;
  if (!isset($account)) {
    $account = $user;
  }

  if(in_array('company', $account->roles)) {
    return TRUE;
  } else {
    return user_view_access($account);
  }
}

/**
 * Implements hook_user_presave().
 */
function ulf_hjoerring_settings_user_presave(&$edit, $account, $category)
{
//  Irrelevant for udsynmodarbejdsliv.dk.
//  if($edit['status'] == 1) {
//    $role = user_role_load_by_name('company');
//    if(isset($edit['roles'][$role->rid]) && $edit['roles'][$role->rid] != 0) {
//      $edit['status'] = 0;
//    }
//  }
}

/**
 * Implements hook_field_default_field_bases_alter().
 */

function ulf_hjoerring_settings_field_default_field_bases_alter(&$fields)
{
  if(isset($fields['field_message_parent_node'])) {
    $fields['field_message_parent_node']['settings']['handler_settings']['target_bundles']['internship'] = 'internship';
    $fields['field_message_parent_node']['settings']['handler_settings']['target_bundles']['education'] = 'education';
  }
}

/**
 * Implements hook_form_alter().
 */
function ulf_hjoerring_settings_form_alter(&$form, &$form_state, $form_id)
{
  // On udsynmodardbejdsliv.dk, the "garantipartner" on user profiles becomes
  // "List virksomhed på søgning", because field_garantipartner is used by the search
  // to decide whether or not to index companies. Companies will have field_garantipartner
  // as TRUE by default, but we should change the label because this site doesn't work with the concept
  // of "garantipartner".
  if ($form_id === 'user_profile_form') {
    if (isset($form['field_garantipartner']['und']['#title'])) {
      $form['field_garantipartner']['und']['#title'] = t('List virksomhed på søgning');
    }
    if (isset($form["field_garantipartner"]["und"]["#default_value"])) {
      $form["field_garantipartner"]["und"]["#default_value"] = 1;
    }
  }
}

function dynamically_change_competencies_options($form, $form_state) {
  return $form['field_competencies'];
}

function ulf_hjoerring_settings_views_default_views_alter(&$views) {
  if(isset($views['ulf_workbench_edits_by_user'])) {
    $view = $views['ulf_workbench_edits_by_user'];
    foreach ($view->display as $id => $display) {
      if($filter = $view->get_item($id, 'filter', 'type')) {
        $filter['value']['internship'] = 'internship';
        $filter['value']['education'] = 'education';
        $view->set_item($id, 'filter', 'type', $filter);
      }
    }
  }
  if(isset($views['ulf_frontpage_promoted_courses'])) {
    $view = $views['ulf_frontpage_promoted_courses'];
    foreach ($view->display as $id => $display) {
      if($filter = $view->get_item($id, 'filter', 'type')) {
        $filter['value']['internship'] = 'internship';
        $filter['value']['education'] = 'education';
        $view->set_item($id, 'filter', 'type', $filter);
      }
    }
  }
}
